name: Integration Apps

on: # yamllint disable-line rule:truthy
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rails:
    name: "${{ matrix.app }} (Ruby ${{ matrix.ruby }})"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {app: rails-six, ruby: "3.0"}
          - {app: rails-seven, ruby: "3.3"}
          - {app: rails-eight, ruby: "3.4"}
    env:
      JOB: integration/${{ matrix.app }}
      MIN: 60
      MAX: 150
    steps: &steps
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .sandbox
      - run: .sandbox/job.sh

  other-apps:
    name: "${{ matrix.app }} (Ruby ${{ matrix.ruby }})"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {app: rack, ruby: "3.4"}
          - {app: sinatra2-classic, ruby: "3.4"}
          - {app: sinatra2-modular, ruby: "3.4"}
          - {app: ruby, ruby: "3.4"}
          - {app: hanami, ruby: "3.3"}
    env:
      JOB: integration/${{ matrix.app }}
      MIN: 30
      MAX: 90
    steps: *steps

  complete:
    name: Integration Apps (complete)
    needs: [rails, other-apps]
    runs-on: ubuntu-24.04
    steps:
      - run: echo ok
