name: Pull Request Labeler

on: # yamllint disable-line rule:truthy
  pull_request:

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-24.04
    env:
      JOB: triage
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .sandbox
      - run: .sandbox/job.sh
