name: System Tests

on: # yamllint disable-line rule:truthy
  pull_request:

permissions:
  contents: read

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - id: changes
        run: echo "changes=true" >> "$GITHUB_OUTPUT"

  build:
    name: Build artifact
    needs: changes
    if: ${{ needs.changes.outputs.changes == 'true' }}
    runs-on: ubuntu-24.04
    env:
      JOB: system-tests/build
      MIN: 60
      MAX: 90
    steps: &steps
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .sandbox
      - run: .sandbox/job.sh

  test:
    name: "System Tests (${{ matrix.scenario }})"
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - DEFAULT
          - APPSEC_BLOCKING
          - APPSEC_API_SECURITY
          - REMOTE_CONFIG
          - TRACING_CONFIG
          - INTEGRATIONS
          - CROSSED_TRACING
          - TELEMETRY
    env:
      JOB: system-tests/${{ matrix.scenario }}
      MIN: 60
      MAX: 240
    steps: *steps

  complete:
    name: System Tests (complete)
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - run: echo ok
