name: Test macOS

on: # yamllint disable-line rule:truthy
  pull_request:

permissions:
  contents: read

jobs:
  test-macos:
    name: "Test (macos-15, ${{ matrix.ruby }})"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ["4.0", "3.4", "3.3", "3.2", "3.1", "3.0"]
    env:
      JOB: macos/${{ matrix.ruby }}
      MIN: 120
      MAX: 240
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .sandbox
      - run: .sandbox/job.sh

  complete:
    name: Test macOS (complete)
    needs: test-macos
    runs-on: ubuntu-24.04
    steps:
      - run: echo ok
